Top_Tomato/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :user_movies

  resources :movies do
    resources :comments
  end

  root 'movies#index'

end

Top_Tomato/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :movie
  belongs_to :user
end

Top_Tomato/app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :comments
  has_many :users, through: :UserMovies
end

Top_Tomato/app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :movies, through: :UserMovies

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :cell, length: { is:10 }, presence: true
  validates :zip, length: { is:5 }, presence: true
end

Top_Tomato/app/models/user_movie.rb
class UserMovie < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :movie, dependent: :destroy
end

Top_Tomato/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Top_Tomato/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:string)
    end
end

Top_Tomato/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :critics_score, :release_date, :poster_url, :synopsis, :created_at, :updated_at)
    end
end

Top_Tomato/app/controllers/user_movies_controller.rb
class UserMoviesController < ApplicationController
  before_action :set_user_movie, only: [:show, :edit, :update, :destroy]

  # GET /user_movies
  # GET /user_movies.json
  def index
    @user_movies = UserMovie.all
  end

  # GET /user_movies/1
  # GET /user_movies/1.json
  def show
  end

  # GET /user_movies/new
  def new
    @user_movie = UserMovie.new
  end

  # GET /user_movies/1/edit
  def edit
  end

  # POST /user_movies
  # POST /user_movies.json
  def create
    @user_movie = UserMovie.new(user_movie_params)

    respond_to do |format|
      if @user_movie.save
        format.html { redirect_to @user_movie, notice: 'User movie was successfully created.' }
        format.json { render :show, status: :created, location: @user_movie }
      else
        format.html { render :new }
        format.json { render json: @user_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_movies/1
  # PATCH/PUT /user_movies/1.json
  def update
    respond_to do |format|
      if @user_movie.update(user_movie_params)
        format.html { redirect_to @user_movie, notice: 'User movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_movie }
      else
        format.html { render :edit }
        format.json { render json: @user_movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_movies/1
  # DELETE /user_movies/1.json
  def destroy
    @user_movie.destroy
    respond_to do |format|
      format.html { redirect_to user_movies_url, notice: 'User movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_movie
      @user_movie = UserMovie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_movie_params
      params[:user_movie]
    end
end

Top_Tomato/app/helpers/application_helper.rb
module ApplicationHelper
end

Top_Tomato/app/helpers/comments_helper.rb
module CommentsHelper
end

Top_Tomato/app/helpers/movies_helper.rb
module MoviesHelper
end

Top_Tomato/app/helpers/user_movies_helper.rb
module UserMoviesHelper
end

Top_Tomato/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :string %><br>
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Top_Tomato/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

Top_Tomato/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.string %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

Top_Tomato/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

Top_Tomato/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>String:</strong>
  <%= @comment.string %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

Top_Tomato/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TopTomato</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>Top Tomatos</h1>
  </header>
  <wrapper>

<%= yield %>
  
  </wrapper>
</body>
</html>

Top_Tomato/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :critics_score %><br>
    <%= f.number_field :critics_score %>
  </div>
  <div class="field">
    <%= f.label :release_date %><br>
    <%= f.text_field :release_date %>
  </div>
  <div class="field">
    <%= f.label :poster_url %><br>
    <%= f.text_field :poster_url %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_area :synopsis %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br>
    <%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <%= f.label :updated_at %><br>
    <%= f.datetime_select :updated_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Top_Tomato/app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

Top_Tomato/app/views/movies/index.html.erb
<div class="wrapper">
  <div class="content">

    <h2>Current Top Movie Releases</h2>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Genre</th>
          <th>Critics score</th>
          <th>Release date</th>
          <th>Poster url</th>
          <th>Synopsis</th>
        </tr>
      </thead>

      <tbody>
        <% @movies.each do |movie| %>
          <tr>
            <td><%= movie.title %></td>
            <td><%= movie.genre %></td>
            <td><%= movie.critics_score %></td>
            <td><%= movie.release_date %></td>
            <td><%= movie.poster_url %></td>
            <td><%= movie.synopsis %></td>
            <td><%= link_to 'Show', movie %></td>
            <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
            <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

Top_Tomato/app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Critics score:</strong>
  <%= @movie.critics_score %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @movie.release_date %>
</p>

<p>
  <strong>Poster url:</strong>
  <%= @movie.poster_url %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @movie.synopsis %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @movie.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @movie.updated_at %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

Top_Tomato/app/views/user_movies/_form.html.erb
<%= form_for(@user_movie) do |f| %>
  <% if @user_movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_movie.errors.count, "error") %> prohibited this user_movie from being saved:</h2>

      <ul>
      <% @user_movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Top_Tomato/app/views/user_movies/edit.html.erb
<h1>Editing user_movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_movie %> |
<%= link_to 'Back', user_movies_path %>

Top_Tomato/app/views/user_movies/index.html.erb
<h1>Listing user_movies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_movies.each do |user_movie| %>
      <tr>
        <td><%= link_to 'Show', user_movie %></td>
        <td><%= link_to 'Edit', edit_user_movie_path(user_movie) %></td>
        <td><%= link_to 'Destroy', user_movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User movie', new_user_movie_path %>

Top_Tomato/app/views/user_movies/new.html.erb
<h1>New user_movie</h1>

<%= render 'form' %>

<%= link_to 'Back', user_movies_path %>

Top_Tomato/app/views/user_movies/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_movie_path(@user_movie) %> |
<%= link_to 'Back', user_movies_path %>